FROM python:3.10.4

ADD setup.py .
ADD README.md .
ADD /src /src
ADD /scripts /scripts
ADD /tests /tests
ADD /models /models

RUN pip3 install ASE numpy tensorflow 
RUN pip install matplotlib rdkit numpy docopt networkx joblib pandas
RUN pip3 install fastapi pydantic uvicorn  
RUN pip3 install python-multipart
RUN python3 setup.py install
ADD api.py .
# CMD ["python3","scripts/example_md_predictor.py","./models/c20/","./models/c20/C20.xyz"]
# CMD ["python3", "fileuploadapi.py"]
ENTRYPOINT ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]